CREATE TRIGGER BeforeEnrollmentInsert ON ENROLLMENT INSTEAD OF INSERT
AS
BEGIN

IF NOT EXISTS(SELECT I.COURSE_ID FROM INSERTED I INNER JOIN COURSE C ON C.Id = I.COURSE_ID AND C.EndDate <= GETDATE()) 
     RAISERROR('Student cannot be enrolled into a course that has ended.',0,1)
ELSE       
			INSERT INTO ENROLLMENT(COURSE_ID, STUDENT_ID)
			(SELECT COURSE_ID, STUDENT_ID FROM INSERTED) 

END

