CREATE PROC GetAvailableHomeworks @StudentID INT
AS
BEGIN
	SELECT [Id], [Name], [NUM_OF_QUESTIONS], STARTDATE, ENDDATE, MAX_TRIES, POINTS_IF_CORRECT, POINTS_IF_WRONG, HOMEWORK_TYPE, ScoreSelection FROM HOMEWORK H INNER JOIN ENROLLMENT E
	ON E.Course_ID = H.COURSE_ID
	WHERE E.STUDENT_ID = @StudentID
	AND H.ENDDATE >= GETDATE()
END