CREATE TABLE [dbo].[COURSE_ASSISTANCE](
	[COURSE_ID] [int] FOREIGN KEY REFERENCES COURSE(id) ON DELETE CASCADE ON UPDATE CASCADE,
	[TA_ID] [int] FOREIGN KEY REFERENCES TeachingAssistant(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT [UNIQUENESS_COURSE_ASSISTANCE] UNIQUE NONCLUSTERED (COURSE_ID, TA_ID)
)