CREATE TABLE [dbo].[ENROLLMENT](
	[COURSE_ID] [int] NOT NULL FOREIGN KEY REFERENCES Course(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	[STUDENT_ID] [int] NOT NULL FOREIGN KEY REFERENCES Student(Id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT [UniqueEnrollment] UNIQUE NONCLUSTERED
    (
        [COURSE_ID], [STUDENT_ID]
    )
)