CREATE TABLE HOMEWORK (
    ID int IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [NAME] varchar(500) NOT NULL,
	COURSE_ID int FOREIGN KEY REFERENCES COURSE(ID),
    NUM_OF_QUESTIONS INT NOT NULL DEFAULT 10,
    STARTDATE DATE NOT NULL,
    ENDDATE   DATE NOT NULL,    
    MAX_TRIES INT NOT NULL,
    POINTS_IF_CORRECT INT NOT NULL,
    POINTS_IF_WRONG INT NOT NULL,
	HOMEWORK_TYPE varchar(20) NOT NULL,
	TOPIC_ID INT FOREIGN KEY REFERENCES Topic(id),
	ScoreSelection VARCHAR(3) NULL,
    CONSTRAINT CheckEndLaterThanStart CHECK (ENDDATE >= STARTDATE),
	CONSTRAINT CHECK_TYPE CHECK (HOMEWORK_TYPE IN ('STANDARD', 'ADAPTIVE'))
)