CREATE TABLE [dbo].[Student]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(30),
	[UserId] VARCHAR(30) UNIQUE NOT NULL,
	[Password] VARCHAR(30) NOT NULL,
	[Level] VARCHAR(30),
	CONSTRAINT [PasswordMinLengthStudent] CHECK (LEN([Password])>=4),
	CONSTRAINT CHECK_LEVEL CHECK ([LEVEL] IN ('SOPHOMORE', 'FRESHMAN', 'JUNIOR', 'SENIOR', 'GRAD', 'UNDERGRAD'))
)